In [60]:
import pandas as pd
import numpy as np

In [61]:
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

In [62]:
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

In [63]:
school_data_complete = pd.merge(school_data, student_data, 
                                how = "left", on = ["school_name", "school_name"] )

In [64]:
school_data_complete.head()

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
3,0,Huang High School,District,2917,1910635,3,Dr. Richard Scott,M,12th,67,58
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84

In [65]:
school_num = len(school_data_complete["school_name"].unique())
student_num = len(school_data_complete["student_name"].unique())
print(f'There are a total of {school_num} schools and {student_num} students')

There are a total of 15 schools and 32715 students

In [66]:
total_budget = school_data["budget"].sum()
print(f'The total budget for the school district is {total_budget}.')

The total budget for the school district is 24649428.

In [67]:
avg_math_score = student_data["math_score"].mean()
avg_reading_score = student_data["reading_score"].mean()
print(f'The average math score is {round(avg_math_score,3)} and the average reading score is {round(avg_reading_score, 3)}.')

avg_score = (avg_math_score + avg_reading_score)/2
print(f'The average total score is {round(avg_score,3)}.')

The average math score is 78.985 and the average reading score is 81.878.
The average total score is 80.432.

In [76]:
math_total_passed = student_data[(student_data['math_score']>=70)].count()['student_name']
reading_total_passed = student_data[(student_data['reading_score']>=70)].count()['student_name']


print(f'The percentage of students that passed the math exam is {round(math_total_passed/student_num, 3)*100}%.')
print(f'The percentage of students that passed the reading exam is {round(reading_total_passed/student_num, 2)*100}%.')

### ??? Hmmmmm ??? ###

The percentage of students that passed the math exam is 89.8%.
The percentage of students that passed the reading exam is 103.0%.

In [79]:
passing_percentage = (math_total_passed + reading_total_passed)/(2*student_num)
#Algebra
print(f'The average total passing percent is {round(passing_percentage,3)*100}%')

### This is still skewed  ###  ??? Hmmmm ???  ###

The average total passing percent is 96.3%

In [82]:
##Yeah yeah
passing_math_percentage = round(math_total_passed/student_num, 3)*100
passing_reading_percentage = round(reading_total_passed/student_num, 2)*100

In [84]:
overview_df = pd.DataFrame({"Total Schools": [school_num], 
                                 "Total Students": [student_num], 
                                 "Total Budget": [total_budget],
                                 "Average Math Score": [avg_math_score], 
                                 "Average Reading Score": [avg_reading_score],
                                 "% Passing Math": [passing_math_percentage],
                                 "% Passing Reading": [passing_percentage],
                                 "% Overall Passing Rate": [passing_percentage]})
overview_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,32715,24649428,78.985371,81.87784,89.8,0.962555,0.962555

In [ ]:
school