In [42]:
import pandas as pd
import numpy as np

In [43]:
schools = "Resources/schools_complete.csv"
students = "Resources/students_complete.csv"

In [44]:
school_data = pd.read_csv(schools)
student_data = pd.read_csv(students)

In [45]:
school_data.head()
#student_data.head()

   School ID            school_name      type  size   budget
0          0      Huang High School  District  2917  1910635
1          1   Figueroa High School  District  2949  1884411
2          2    Shelton High School   Charter  1761  1056600
3          3  Hernandez High School  District  4635  3022020
4          4    Griffin High School   Charter  1468   917500

In [46]:
combined_data = pd.merge(school_data, student_data, on = ["school_name", "school_name"])
#combined_data_df = pd.DataFrame(combined_data)
combined_data.head()

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
3,0,Huang High School,District,2917,1910635,3,Dr. Richard Scott,M,12th,67,58
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84

In [52]:
global_avg_math_score = round((combined_data['math_score'].sum())/(len(combined_data['student_name'])),3)
global_avg_reading_score = round((combined_data['reading_score'].sum())/(len(combined_data['student_name'])),3)

print(f'The average math score for all students was {global_avg_math_score}.')
print(f'The average reading score for all students was {global_avg_reading_score}.')

The average math score for all students was 78.985.
The average reading score for all students was 81.878.

In [154]:
total_school = len(combined_data['school_name'].unique())
total_students = len(combined_data['student_name'])
print(f'There are {total_school} schools with a total of {total_students} students.')
total_budget = school_data['budget'].sum()
print(total_budget)

There are 15 schools with a total of 39170 students.
24649428

In [141]:
passing_math_count = combined_data[(combined_data["math_score"] >= 70)].count()["student_name"]
passing_math_percentage = round(passing_math_count / float(total_students) * 100,3)
passing_reading_count = combined_data[(combined_data["reading_score"] >= 70)].count()["student_name"]
passing_reading_percentage = round(passing_reading_count / float(total_students) * 100,3)

In [143]:
print(f'{passing_math_percentage}% and {passing_reading_percentage}%')

74.981% and 85.805%

In [145]:
District_overview = pd.DataFrame({"Total Schools": [total_school], "Total Students": [total_students], 
                                  "Percent passing math": [passing_math_percentage], "Percent passing reading":[passing_reading_percentage], "Total Budget": [total_budget] })
District_overview

NameError: name 'total_budget' is not defined